server:
  servlet:
    contextPath: /SBRestCrudApplication
  port: 8080

spring:
  application:
    name: sb-rest-crud-application
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: root
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.shobhit: DEBUG
  file.name: /Users/shobhitbhardwaj/WorkSpace/JavaWorkSpace/app-logs/sb-rest-crud.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss} - %msg%n"

#	Docker MySql Config
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://mysql-standalone:3306/test_db
#spring.datasource.username=sa
#spring.datasource.password=password

#	Local MySql Config
#spring.datasource.url=jdbc:mysql://localhost:3306/test_db
#spring.datasource.username=root
#spring.datasource.password=root

hibernate:
  format_sql: true

management:
  server.port: 8082
  endpoints.web.exposure.include: "*"
#endpoint.shutdown.enabled: true
